function consoleGr () {
	console.group ('Level')
	console.log ('Hello')
	console.group ('New Level')
	console.log ('Nihao')
	console.group ('Next Level')
	console.log ('Hola')
	console.group ('More Level')
	console.log ('Yahho Hisashiburi')
	console.log ('Jaa')
	console.groupEnd ()
	console.log ('Hasta luego')
	console.groupEnd ()
	console.log ('Zai Zen')
	console.groupEnd ()
	console.log ('Bye')
	console.groupEnd ()
}